In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error as mae

In [3]:
df = pd.read_csv("E:/pps project/Real Estate Price Prediction/data/final.csv")

In [4]:
df.head()

AREA  INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  \
0  Karapakkam      1004            131          1           1       3   
1  Anna Nagar      1986             26          2           1       5   
2       Adyar       909             70          1           1       3   
3   Velachery      1855             14          3           2       5   
4  Karapakkam      1226             84          1           1       3   

  SALE_COND PARK_FACIL   BUILDTYPE UTILITY_AVAIL  STREET MZZONE  QS_ROOMS  \
0  AbNormal        Yes  Commercial        AllPub   Paved      A       4.0   
1  AbNormal         No  Commercial        AllPub  Gravel     RH       4.9   
2  AbNormal        Yes  Commercial           ELO  Gravel     RL       4.1   
3    Family         No      Others       NoSewr    Paved      I       4.7   
4  AbNormal        Yes      Others        AllPub  Gravel      C       3.0   

   QS_BEDROOM  SALES_PRICE  
0         4.9      7600000  
1         2.5     21717770  
2         2.2     13159200  
3         3.6      9630290  
4         4.1      7406250

In [5]:
df_n = pd.get_dummies(df)

In [6]:
x = df_n.drop("SALES_PRICE",axis=1)
y = df_n["SALES_PRICE"]

In [7]:
linreg = LinearRegression()

In [8]:
poly = PolynomialFeatures(degree = 2)

In [9]:
X = poly.fit_transform(x)

In [10]:
print(X)

[[1.000e+00 1.004e+03 1.310e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.986e+03 2.600e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 9.090e+02 7.000e+01 ... 1.000e+00 0.000e+00 0.000e+00]
 ...
 [1.000e+00 1.614e+03 1.520e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 7.870e+02 4.000e+01 ... 1.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.896e+03 1.560e+02 ... 0.000e+00 0.000e+00 0.000e+00]]


In [11]:
linreg.fit(X,y)

LinearRegression()

In [12]:
res = linreg.predict(X)

In [13]:
print(mae(res,y))

183460.11461403518


In [14]:
res

array([ 7873961.18638625, 21336605.89990485, 13108484.45538138, ...,
        8129474.43106066,  8412281.41348767, 10309042.61322707])

In [15]:
df.iloc[0]

AREA             Karapakkam
INT_SQFT               1004
DIST_MAINROAD           131
N_BEDROOM                 1
N_BATHROOM                1
N_ROOM                    3
SALE_COND          AbNormal
PARK_FACIL              Yes
BUILDTYPE        Commercial
UTILITY_AVAIL        AllPub
STREET                Paved
MZZONE                    A
QS_ROOMS                  4
QS_BEDROOM              4.9
SALES_PRICE         7600000
Name: 0, dtype: object

In [16]:
df.dtypes

AREA              object
INT_SQFT           int64
DIST_MAINROAD      int64
N_BEDROOM          int64
N_BATHROOM         int64
N_ROOM             int64
SALE_COND         object
PARK_FACIL        object
BUILDTYPE         object
UTILITY_AVAIL     object
STREET            object
MZZONE            object
QS_ROOMS         float64
QS_BEDROOM       float64
SALES_PRICE        int64
dtype: object

In [17]:
temp = pd.DataFrame(df.iloc[0])

In [18]:
temp

0
AREA           Karapakkam
INT_SQFT             1004
DIST_MAINROAD         131
N_BEDROOM               1
N_BATHROOM              1
N_ROOM                  3
SALE_COND        AbNormal
PARK_FACIL            Yes
BUILDTYPE      Commercial
UTILITY_AVAIL      AllPub
STREET              Paved
MZZONE                  A
QS_ROOMS                4
QS_BEDROOM            4.9
SALES_PRICE       7600000

In [19]:
temp

0
AREA           Karapakkam
INT_SQFT             1004
DIST_MAINROAD         131
N_BEDROOM               1
N_BATHROOM              1
N_ROOM                  3
SALE_COND        AbNormal
PARK_FACIL            Yes
BUILDTYPE      Commercial
UTILITY_AVAIL      AllPub
STREET              Paved
MZZONE                  A
QS_ROOMS                4
QS_BEDROOM            4.9
SALES_PRICE       7600000

In [20]:
abc = {"INT_SQFT":1004,"DIST_MAINROAD":131,"N_BEDROOM":1,"N_BATHROOM":1,"N_ROOM":3,"QS_ROOMS":4,"QS_BEDROOM":4.9,"AREA":"Karapakkam","SALE_COND":"AbNormal","PARK_FACIL":"Yes","BUILDTYPE":"Commercial","UTILITY":"AllPub","STREET":"Paved","MZZONE":"A"}

In [21]:
import json

In [22]:
abc = json.dumps(abc)

In [23]:
abc

'{"INT_SQFT": 1004, "DIST_MAINROAD": 131, "N_BEDROOM": 1, "N_BATHROOM": 1, "N_ROOM": 3, "QS_ROOMS": 4, "QS_BEDROOM": 4.9, "AREA": "Karapakkam", "SALE_COND": "AbNormal", "PARK_FACIL": "Yes", "BUILDTYPE": "Commercial", "UTILITY": "AllPub", "STREET": "Paved", "MZZONE": "A"}'

In [24]:
list1 = [["Karapakkam",1004,131,1,1,3,"AbNormal","Yes","Commercial","AllPub","Paved","A",4,4.9]]

In [30]:
col = ['AREA', 'INT_SQFT', 'DIST_MAINROAD', 'N_BEDROOM', 'N_BATHROOM','N_ROOM', 'SALE_COND', 'PARK_FACIL', 'BUILDTYPE', 'UTILITY','STREET', 'MZZONE', 'QS_ROOMS', 'QS_BEDROOM']

In [31]:
temp = pd.DataFrame(list1,columns=col)

In [32]:
temp

AREA  INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  \
0  Karapakkam      1004            131          1           1       3   

  SALE_COND PARK_FACIL   BUILDTYPE UTILITY STREET MZZONE  QS_ROOMS  QS_BEDROOM  
0  AbNormal        Yes  Commercial  AllPub  Paved      A         4         4.9

In [33]:
temp1 = pd.get_dummies(temp)

In [34]:
temp1

INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  QS_ROOMS  \
0      1004            131          1           1       3         4   

   QS_BEDROOM  AREA_Karapakkam  SALE_COND_AbNormal  PARK_FACIL_Yes  \
0         4.9                1                   1               1   

   BUILDTYPE_Commercial  UTILITY_AllPub  STREET_Paved  MZZONE_A  
0                     1               1             1         1

In [35]:
df_1 = pd.get_dummies(df)

In [36]:
df_1.columns

Index(['INT_SQFT', 'DIST_MAINROAD', 'N_BEDROOM', 'N_BATHROOM', 'N_ROOM',
       'QS_ROOMS', 'QS_BEDROOM', 'SALES_PRICE', 'AREA_Adyar',
       'AREA_Anna Nagar', 'AREA_Chrompet', 'AREA_KK Nagar', 'AREA_Karapakkam',
       'AREA_T Nagar', 'AREA_Velachery', 'SALE_COND_AbNormal',
       'SALE_COND_AdjLand', 'SALE_COND_Family', 'SALE_COND_Normal Sale',
       'SALE_COND_Partial', 'PARK_FACIL_No', 'PARK_FACIL_Yes',
       'BUILDTYPE_Commercial', 'BUILDTYPE_House', 'BUILDTYPE_Others',
       'UTILITY_AVAIL_AllPub', 'UTILITY_AVAIL_ELO', 'UTILITY_AVAIL_NoSeWa',
       'UTILITY_AVAIL_NoSewr ', 'STREET_Gravel', 'STREET_No Access',
       'STREET_Paved', 'MZZONE_A', 'MZZONE_C', 'MZZONE_I', 'MZZONE_RH',
       'MZZONE_RL', 'MZZONE_RM'],
      dtype='object')

In [37]:
query = temp1.reindex(columns=df_1.columns, fill_value=0)

In [38]:
query

INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  QS_ROOMS  \
0      1004            131          1           1       3         4   

   QS_BEDROOM  SALES_PRICE  AREA_Adyar  AREA_Anna Nagar  ...  \
0         4.9            0           0                0  ...   

   UTILITY_AVAIL_NoSewr   STREET_Gravel  STREET_No Access  STREET_Paved  \
0                      0              0                 0             1   

   MZZONE_A  MZZONE_C  MZZONE_I  MZZONE_RH  MZZONE_RL  MZZONE_RM  
0         1         0         0          0          0          0  

[1 rows x 38 columns]

In [39]:
query.drop("SALES_PRICE",axis=1,inplace=True)

In [40]:
query

INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  QS_ROOMS  \
0      1004            131          1           1       3         4   

   QS_BEDROOM  AREA_Adyar  AREA_Anna Nagar  AREA_Chrompet  ...  \
0         4.9           0                0              0  ...   

   UTILITY_AVAIL_NoSewr   STREET_Gravel  STREET_No Access  STREET_Paved  \
0                      0              0                 0             1   

   MZZONE_A  MZZONE_C  MZZONE_I  MZZONE_RH  MZZONE_RL  MZZONE_RM  
0         1         0         0          0          0          0  

[1 rows x 37 columns]

In [41]:
x1 = poly.fit_transform(query)

In [42]:
x1

array([[1.000000e+00, 1.004000e+03, 1.310000e+02, 1.000000e+00,
        1.000000e+00, 3.000000e+00, 4.000000e+00, 4.900000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.008016e+06, 1.315240e+05,
        1.004000e+03, 1.004000e+03, 3.012000e+03, 4.016000e+03,
        4.919600e+03, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 1.004000e+03, 0.000000e+00, 0.000000e+00,
        1.004000e+03, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.004000e+03, 1.004000e+03,
        0.000000e+00, 0.000000e+00, 0.00

In [43]:
temp_res = linreg.predict(x1)

In [44]:
df_n

INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  QS_ROOMS  \
0         1004            131          1           1       3       4.0   
1         1986             26          2           1       5       4.9   
2          909             70          1           1       3       4.1   
3         1855             14          3           2       5       4.7   
4         1226             84          1           1       3       3.0   
...        ...            ...        ...         ...     ...       ...   
7093       598             51          1           1       2       3.0   
7094      1897             52          3           2       5       3.6   
7095      1614            152          2           1       4       4.3   
7096       787             40          1           1       2       4.6   
7097      1896            156          3           2       5       3.1   

      QS_BEDROOM  SALES_PRICE  AREA_Adyar  AREA_Anna Nagar  ...  \
0            4.9      7600000           0                0  ...   
1            2.5     21717770           0                1  ...   
2            2.2     13159200           1                0  ...   
3            3.6      9630290           0                0  ...   
4            4.1      7406250           0                0  ...   
...          ...          ...         ...              ...  ...   
7093         2.4      5353000           0                0  ...   
7094         3.3     10818480           0                0  ...   
7095         2.9      8351410           0                0  ...   
7096         4.1      8507000           0                0  ...   
7097         4.3      9976480           0                0  ...   

      UTILITY_AVAIL_NoSewr   STREET_Gravel  STREET_No Access  STREET_Paved  \
0                         0              0                 0             1   
1                         0              1                 0             0   
2                         0              1                 0             0   
3                         1              0                 0             1   
4                         0              1                 0             0   
...                     ...            ...               ...           ...   
7093                      0              0                 1             0   
7094                      0              0                 1             0   
7095                      0              1                 0             0   
7096                      0              0                 0             1   
7097                      0              0                 0             1   

      MZZONE_A  MZZONE_C  MZZONE_I  MZZONE_RH  MZZONE_RL  MZZONE_RM  
0            1         0         0          0          0          0  
1            0         0         0          1          0          0  
2            0         0         0          0          1          0  
3            0         0         1          0          0          0  
4            0         1         0          0          0          0  
...        ...       ...       ...        ...        ...        ...  
7093         0         0         0          0          0          1  
7094         0         0         0          1          0          0  
7095         0         0         1          0          0          0  
7096         0         0         0          0          1          0  
7097         0         0         1          0          0          0  

[7098 rows x 38 columns]

In [45]:
temp_res

array([7338447.3916051])

a = [[1.000000e+00, 1.004000e+03, 1.310000e+02, 1.000000e+00, 1.000000e+00,
  3.000000e+00, 4.000000e+00, 4.900000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00 ,0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.008016e+06, 1.315240e+05,
  1.004000e+03, 1.004000e+03, 3.012000e+03, 4.016000e+03, 4.919600e+03,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.004000e+03,
  0.000000e+00, 0.000000e+00, 1.004000e+03, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.004000e+03, 1.004000e+03,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.004000e+03, 1.004000e+03,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.716100e+04, 1.310000e+02, 1.310000e+02, 3.930000e+02, 5.240000e+02,
  6.419000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.310000e+02, 0.000000e+00, 0.000000e+00, 1.310000e+02, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.310000e+02,
  1.310000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.310000e+02,
  1.310000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 3.000000e+00, 4.000000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 3.000000e+00, 4.000000e+00, 4.900000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  9.000000e+00, 1.200000e+01, 1.470000e+01, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 3.000000e+00, 0.000000e+00, 0.000000e+00,
  3.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 3.000000e+00, 3.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 3.000000e+00, 3.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.600000e+01, 1.960000e+01,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 4.000000e+00,
  0.000000e+00, 0.000000e+00, 4.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 4.000000e+00, 4.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 4.000000e+00, 4.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  2.401000e+01, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 4.900000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 4.900000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 4.900000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00]]

In [46]:
a = [[1.000000e+00, 1.004000e+03, 1.310000e+02, 1.000000e+00, 1.000000e+00,
  3.000000e+00, 4.000000e+00, 4.900000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00 ,0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.008016e+06, 1.315240e+05,
  1.004000e+03, 1.004000e+03, 3.012000e+03, 4.016000e+03, 4.919600e+03,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.004000e+03,
  0.000000e+00, 0.000000e+00, 1.004000e+03, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.004000e+03, 1.004000e+03,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.004000e+03, 1.004000e+03,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.716100e+04, 1.310000e+02, 1.310000e+02, 3.930000e+02, 5.240000e+02,
  6.419000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.310000e+02, 0.000000e+00, 0.000000e+00, 1.310000e+02, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.310000e+02,
  1.310000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.310000e+02,
  1.310000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 3.000000e+00, 4.000000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 3.000000e+00, 4.000000e+00, 4.900000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  9.000000e+00, 1.200000e+01, 1.470000e+01, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 3.000000e+00, 0.000000e+00, 0.000000e+00,
  3.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 3.000000e+00, 3.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 3.000000e+00, 3.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.600000e+01, 1.960000e+01,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 4.000000e+00,
  0.000000e+00, 0.000000e+00, 4.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 4.000000e+00, 4.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 4.000000e+00, 4.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  2.401000e+01, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 4.900000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 4.900000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 4.900000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00]]

In [47]:
x1

array([[1.000000e+00, 1.004000e+03, 1.310000e+02, 1.000000e+00,
        1.000000e+00, 3.000000e+00, 4.000000e+00, 4.900000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.008016e+06, 1.315240e+05,
        1.004000e+03, 1.004000e+03, 3.012000e+03, 4.016000e+03,
        4.919600e+03, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 1.004000e+03, 0.000000e+00, 0.000000e+00,
        1.004000e+03, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.004000e+03, 1.004000e+03,
        0.000000e+00, 0.000000e+00, 0.00

In [48]:
a

[[1.0,
  1004.0,
  131.0,
  1.0,
  1.0,
  3.0,
  4.0,
  4.9,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1008016.0,
  131524.0,
  1004.0,
  1004.0,
  3012.0,
  4016.0,
  4919.6,
  0.0,
  0.0,
  0.0,
  0.0,
  1004.0,
  0.0,
  0.0,
  1004.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1004.0,
  1004.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1004.0,
  1004.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  17161.0,
  131.0,
  131.0,
  393.0,
  524.0,
  641.9,
  0.0,
  0.0,
  0.0,
  0.0,
  131.0,
  0.0,
  0.0,
  131.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  131.0,
  131.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  131.0,
  131.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  3.0,
  4.0,
  4.9,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0,
 

In [49]:
a1 = (a)

In [50]:
a1 = np.array(a)

In [51]:
a1

array([[1.000000e+00, 1.004000e+03, 1.310000e+02, 1.000000e+00,
        1.000000e+00, 3.000000e+00, 4.000000e+00, 4.900000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.008016e+06, 1.315240e+05,
        1.004000e+03, 1.004000e+03, 3.012000e+03, 4.016000e+03,
        4.919600e+03, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 1.004000e+03, 0.000000e+00, 0.000000e+00,
        1.004000e+03, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.004000e+03, 1.004000e+03,
        0.000000e+00, 0.000000e+00, 0.00

In [53]:
xasd = linreg.predict(a1)

In [54]:
xasd

array([7338447.3916051])

In [55]:
net = [[1.000000e+00, 1.004000e+03, 1.310000e+02, 1.000000e+00, 1.000000e+00,
  3.000000e+00, 4.000000e+00, 4.900000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.008016e+06, 1.315240e+05,
  1.004000e+03, 1.004000e+03, 3.012000e+03, 4.016000e+03, 4.919600e+03,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  1.716100e+04, 1.310000e+02, 1.310000e+02, 3.930000e+02, 5.240000e+02,
  6.419000e+02, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 1.000000e+00, 3.000000e+00, 4.000000e+00,
  4.900000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 1.000000e+00, 3.000000e+00, 4.000000e+00, 4.900000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  9.000000e+00, 1.200000e+01, 1.470000e+01, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 1.600000e+01, 1.960000e+01,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  2.401000e+01, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
  0.000000e+00]]

In [56]:
net = np.array(net)

In [58]:
net_ans = linreg.predict(net)

In [60]:
net_ans

array([5437995.21356652])